### ISSUE TITLE
Replace rg by grep

### ISSUE THREAD

**Issue by JadeKharats** [stephendolan/lucky_jumpstart#141]
In the script / rename_template_app script, I think the grep command could be more easily compatible.

replace
rg lucky_jumpstart -l | xargs sed -i "" "s/lucky_jumpstart/$NEW_APP_NAME/g"
rg "Lucky Jumpstart" -l | xargs sed -i "" "s/Lucky Jumpstart/$NEW_APP_NAME/g"

by
grep -rl lucky_jumpstart  | xargs sed -i "" "s/lucky_jumpstart/$NEW_APP_NAME/g"
grep -rl "Lucky Jumpstart" | xargs sed -i "" "s/Lucky Jumpstart/$NEW_APP_NAME/g"

What do you think about?

**Comment by stephendolan** [comment]
Closed with https://github.com/stephendolan/lucky_jumpstart/commit/183b60f5d701e37a9385241697fae366d71f2c33

Thanks for the suggestion and sample code, @JadeKharats. Had to make a few modifications to get it working, but it was very helpful.
