### ISSUE TITLE
Lucky jumpstart does not work out of the box (due to PG issue)

### ISSUE THREAD

**Issue by vjousse** [stephendolan/lucky_jumpstart#186]
If you use the repo out of the box, it can't work as `./script/setup` requires you to have a working Postgres listening on port `5432`. If you do so, the `lucky dev` script will fail to start as docker will complain that the port `5432` is already used (by your local Postgres).

Maybe modifying the initial `script/setup` script to use docker would be better?

**Comment by stephendolan** [comment]
Thanks for opening this, @vjousse! It's been on my list for a while, but I've gotten so used to setting the project up that I haven't prioritized it yet 😄
