### ISSUE TITLE
Your sponsor information is copied when using the template

### ISSUE THREAD

**Issue by matthewmcgarvey** [stephendolan/lucky_jumpstart#606]
Example: https://github.com/matthewmcgarvey/asdf-test

Maybe this is intentional, but if not is there a way to avoid that being in the resulting repo?

**Comment by stephendolan** [comment]
Thanks, Matthew! I hadn't noticed this in my own use, and I'm 99% sure that GitHub doesn't have a way to omit specific files from being copied. 

We could remove it in the setup script, but I'm also fine with removing it from the repo altogether.
