### ISSUE TITLE
esbuild does not have cache busting

### ISSUE THREAD

**Issue by grepsedawk** [stephendolan/lucky_jumpstart#661]
This becomes an issue locally during dev, requiring hard, cache busted refreshes to develop css/js locally
And during production, the clients cache causes these assets to not be reloaded/busted
Implementing some sort of cache bust on esbuild would be nice for this jumpstart

**Comment by stephendolan** [comment]
Thanks for opening the issue @grepsedawk!

Can you provide more details about the behavior that you're seeing? I'm unable to reproduce with this workflow:

1. Start the Lucky Jumpstart dev server with `lucky dev`.
1. Open the user profile edit page and add `data_controller: "hello"` to a div there.
1. Verify that after compile, a console message is shown.
1. Edited the console message **in the JS file**.
1. Verified that the new message is displayed without a manual refresh (via BrowserSync).
1. Edited `app.css` to make all `div` elements have a blue background.
1. Verified that the page has blue backgrounds on all divs without a manual refresh (via BrowserSync).

Happy to reopen this with some exact steps you can run against this repo in development to reproduce.

**Comment by grepsedawk** [comment]
Ah, so on the dev side it _does_ browsersync proper, but if you manually reload the page without flushing caches, it shows an original copy of the asset

**Comment by stephendolan** [comment]
@grepsedawk Still not 100% sure how to reproduce, so if you can outline the steps from a fresh Jumpstart clone I'll take a look!
