### ISSUE TITLE
The github actions point to deprecated crystal install

### ISSUE THREAD

**Issue by jwoertink** [stephendolan/lucky_jumpstart#694]
https://github.com/stephendolan/lucky_jumpstart/blob/fa45d0b0d56b9524092c05fa435c04bcd3876e8b/.github/workflows/lucky.yml#L15

This should now just go to the official one https://github.com/crystal-lang/install-crystal

**Comment by stephendolan** [comment]
Fixed in https://github.com/stephendolan/lucky_jumpstart/commit/ffbeb57a4f79c1baae216f787af0bc2fff5c373a
