### ISSUE TITLE
Lucky command called before shards installed in script/setup

### ISSUE THREAD

**Issue by matthewmcgarvey** [stephendolan/lucky_jumpstart#701]
https://github.com/stephendolan/lucky_jumpstart/blob/36e5c6ed54d8dcbe61d74f3aa30bea6601e2f75f/script/setup#L10
https://github.com/stephendolan/lucky_jumpstart/blob/36e5c6ed54d8dcbe61d74f3aa30bea6601e2f75f/script/system_check#L29-L31

`lucky ensure_process_runner_installed` tries to compile the app tasks but fails because `shards install` needs to be run first.

**Comment by stephendolan** [comment]
Closed in https://github.com/stephendolan/lucky_jumpstart/commit/7a15d2a15e5320ac7d4068238bfbd65c3843abee
